version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - t-ober
  - sebastian-peter
  - danielfeismann
  - jo-bao
  - staudtMarius
  ignore:
    - dependency-name: org.scalatest:scalatest_2.13
      versions:
        - 3.3.0-SNAP+
    - dependency-name: org.scalatestplus:mockito-3-4_2.13
      versions:
        - 3.3.0.0-SNAP+

- package-ecosystem: pip
  directory: "/docs/readthedocs"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 8
  target-branch: dev
