apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: simona
    user: admin
    password: admin
    url: http://influxdb:8086
    isDefault: true
    editable: true